spring:
  application:
    name: secure-discovery

server:
  port: 8761
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:MyServer.jks
    key-store-password: Modern123$
    trust-store: classpath:MyServer.jks
    trust-store-password: Modern123$
    
eureka:
  instance:
    hostname: localhost
    securePort: ${server.port}
    securePortEnabled: true  
    nonSecurePortEnabled: false
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/admin/info
  client:
    registerWithEureka: false
    fetchRegistry: false